image: node:latest

cache:
  paths:
    - node_modules

stages:          
  - build
  - test
  - report
  - deploy

build:       
  stage: build
  before_script:
    - npm install
  script:
    - echo "Compiling the code..."
    - npm run compile
    - echo "Compile complete."
  artifacts:
    paths:
      - artifacts

audit-slither-test: 
  stage: test
  needs: []
  before_script:
    - npm install
    - apt-get update && apt-get install -y python3-pip
    - pip3 install slither-analyzer
  script:
    - echo "Running slither..."
    - slither .
  allow_failure: true

lint-test:   
  stage: test 
  needs: []
  before_script:
      - npm install   
  script:
    - echo "Linting code..."
    - npm run lint 
    - echo "No lint issues found."

unit-test:   
  stage: test
  needs: []
  before_script:
    - npm install    
  script:
    - echo "Running unit tests... "
    - npm run test

coverage:
  stage: report
  needs: []
  before_script:
    - npm install 
  script:
    - echo "Generating code coverage report..."
    - npm run coverage
  artifacts:
    paths:
      - coverage
  allow_failure: true

gas-report:
  stage: report
  needs: []
  before_script:
    - npm install
  script:
    - echo "Generating gas report..."
    - npm run test # creates gas-report.txt
    - echo "<pre>" > gas-report/index.html
    - npx ansi-to-html gas-report.txt --fg black --bg white >> gas-report.html
  artifacts:
    paths:
      - gas-report.html

deploy:      
  stage: deploy
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."



